### ISSUE TITLE
commit "Use deprecated style loading" has broken iron-cropper

### ISSUE THREAD

**Issue by sethpkendall** [safetychanger/iron-cropper#3]
I was using this polymer element 2 days ago and then the commit yesterday broke it. Is the style loading going to be updated to function again?

**Comment by rubenstolk** [comment]
Hi @sethpkendall it should still work... which Polymer version are you on?

**Comment by rubenstolk** [comment]
@sethpkendall in any case you can resort to fixed version `1.0.0`

**Comment by sethpkendall** [comment]
Im using Polymer 1.4.0. I was sure it was a problem with my implementation until I saw that the demo on webcomponent.org is no longer working either.

**Comment by rubenstolk** [comment]
Hi @sethpkendall you're right indeed, it contained a nasty bug. I've updated `master` and `1.0.1` branch, will work now!
