### ISSUE TITLE
Duplicated image instead of cropbox

### ISSUE THREAD

**Issue by jonathan-bibas** [safetychanger/iron-cropper#4]
Hi, i'm using your component wich seem wonderfull in the demo but when i integrate it in my project it render a double image without all the cropping stuff:

![sans titre](https://cloud.githubusercontent.com/assets/7620241/23403460/e6450ae4-fdb8-11e6-8b6d-009f413b5127.png)

Do you know what's going on?

**Comment by jonathan-bibas** [comment]
Problem found: I had to add the shadow dom to the demo index, also i seen this isn't working on firefox

**Comment by rubenstolk** [comment]
Just rolled an update to support `shady` dom. Needed to apply a hack to prevent the container height to go mad but I guess this should work now.
