### ISSUE TITLE
Problem when changing src

### ISSUE THREAD

**Issue by jonathan-bibas** [safetychanger/iron-cropper#5]
Hi,
When changing the src propertie, the image is limited by height.
My solution working: add observer on src property to trigger 'render' function

**Comment by jonathan-bibas** [comment]
When working on, i seen the problem is in the line: `wrapper.setAttribute('style', 'max-height: ' + this.$.image.offsetHeight + 'px');`.

`this.$.image.offsetHeight` isn't representing the loaded file, may be the function fire before the image is realy loaded?

**Comment by rubenstolk** [comment]
@jonathan-bibas thanks for the bug report!

**Comment by jonathan-bibas** [comment]
@rubenstolk Thanks to you for a so good job!
