### ISSUE TITLE
Polymer 2.0?

### ISSUE THREAD

**Issue by yairopro** [safetychanger/iron-cropper#8]
Hello
Here's an update of the component to Polymer 2.0: [iron-cropper.html.txt](https://github.com/safetychanger/iron-cropper/files/1117863/iron-cropper.html.txt)
User gets the crop dimenssions via the `dimenssions` property, using data-binding.
What do you think  about? =)

**Comment by rubenstolk** [comment]
Hey, feel free to send a PR
